### ISSUE TITLE
Fileshare without snapshot and access cannot be deleted.

### ISSUE THREAD

**Issue by sfzeng** [opensds/opensds#884]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
I chose three  fileshares without snapshot and access to delete, while two fileshares be  deleted, one fileshare is left with status set to be 'errorDeleting'.
![delete-error-0617](https://user-images.githubusercontent.com/38932432/59591793-43442b00-9121-11e9-8190-821359f4fbd2.png)

**What you expected to happen**:
All fileshares can be deleted successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Choose several fileshares and delete them at the same time.

**Anything else we need to know?**:
I had 7 fileshares, 4 have no snapshot while 3 have snapshot.  In the beginning, I chose 7 fileshares to delete, 4 fileshares were deleted while 3 left as expected, but after that, I chose all these 3 fileshares to delete, I got the error described before.

**Environment**:
- Hotpot(release/branch) version: development branch
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic
- Install tools: manually
- Others:  dash-board: development branch

**Comment by wisererik** [comment]
I think it's same issue as another issue I mentioned: #863

**Comment by leonwanghui** [comment]
I think it's already fixed by https://github.com/opensds/opensds-dashboard/pull/126, please have a test.

**Comment by sfzeng** [comment]
@leonwanghui No, it's a different issue, and I tested with the latest codes, this issue still exists.

**Comment by leonwanghui** [comment]
Related to #863

**Comment by PravinRanjan10** [comment]
I think your concern is, if a fileshare have snapshot, it should not deleted. First snapshot should be deleted then fileshare.
This issue is already fixed in dashboard and API level. Please check and close this.
